| Algorithm                      | Mechanism/Working                                                                                                                                                    | Time Complexity                                 | Common Uses/Applications                                                                                   |
|--------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------|------------------------------------------------------------------------------------------------------------|
| **Brute-Force (Naive)**        | Checks every possible position in the text for the pattern by sliding it one character at a time.                                                                    | **Worst-case:** O(nm)                          | Small texts/patterns, simple implementations.                                                              |
| **Knuth-Morris-Pratt (KMP)**   | Preprocesses the pattern to create a "Longest Prefix Suffix" (LPS) array to skip unnecessary comparisons during matching.                                           | **Preprocessing:** O(m); **Matching:** O(n)    | DNA sequence alignment, plagiarism detection, and text editors.                                            |
| **Rabin-Karp**                 | Uses hashing to compare the hash of the pattern with substrings of the text. Employs rolling hash for efficiency.                                                   | **Average:** O(n + m); **Worst-case:** O(nm)   | Multiple pattern matching (e.g., spam filters), document similarity checks.                                |
| **Boyer-Moore**                | Combines two heuristics: "Bad Character" (skips mismatched characters) and "Good Suffix" (matches suffixes). Processes the pattern from right to left.               | **Best:** O(n/m); **Worst-case:** O(nm)        | Search engines, text editors (e.g., "Find" in Notepad).                                                   |
| **Finite Automaton**           | Constructs a state machine from the pattern. Transitions between states represent matches/mismatches as the text is processed.                                      | **Preprocessing:** O(m\|Σ\|); **Matching:** O(n) | Regular expression engines, network intrusion detection.                                                   |
| **Aho-Corasick**               | Builds a trie with failure links to efficiently match multiple patterns simultaneously. Combines trie traversal with KMP-like failure transitions.                  | **Preprocessing:** O(Σk); **Matching:** O(n + z) | Virus signature scanning, keyword highlighting, and bioinformatics.                                        |
| **Z-Algorithm**                | Computes the Z-array for the text, which stores the length of the longest substring starting at each position that matches the pattern's prefix.                     | **Preprocessing:** O(n + m); **Matching:** O(n + m) | Pattern preprocessing, substring searches in large texts.                                                  |
